#!/usr/bin/env python3
"""Add a small, contrast-aware generator attribution to an image."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, ImageStat


FONT_CANDIDATES = (
    "/System/Library/Fonts/Supplemental/Arial.ttf",
    "/System/Library/Fonts/Supplemental/Helvetica.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
)


def load_font(size: int, requested: str | None) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates = (requested,) if requested else FONT_CANDIDATES
    for candidate in candidates:
        if candidate and Path(candidate).is_file():
            return ImageFont.truetype(candidate, size=size)
    return ImageFont.load_default(size=size)


def add_attribution(
    source: Path,
    destination: Path,
    generator: str,
    font_path: str | None = None,
) -> None:
    label = f"This image generated by {generator}."
    image = Image.open(source).convert("RGBA")
    width, height = image.size
    font_size = max(13, round(width * 0.013))
    margin = max(12, round(width * 0.014))
    font = load_font(font_size, font_path)

    overlay = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)
    bounds = draw.textbbox((0, 0), label, font=font, stroke_width=1)
    text_width = bounds[2] - bounds[0]
    text_height = bounds[3] - bounds[1]
    left = width - margin - text_width
    top = height - margin - text_height

    sample_padding = max(4, round(font_size * 0.25))
    sample_box = (
        max(0, left - sample_padding),
        max(0, top - sample_padding),
        min(width, width - margin + sample_padding),
        min(height, height - margin + sample_padding),
    )
    luminance = ImageStat.Stat(image.crop(sample_box).convert("L")).mean[0]
    if luminance < 145:
        fill = (248, 248, 248, 220)
        stroke = (0, 0, 0, 170)
    else:
        fill = (18, 18, 18, 220)
        stroke = (255, 255, 255, 170)

    draw.text(
        (left - bounds[0], top - bounds[1]),
        label,
        font=font,
        fill=fill,
        stroke_width=1,
        stroke_fill=stroke,
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    Image.alpha_composite(image, overlay).save(destination)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Watermark a generated image with a contrast-aware attribution."
    )
    parser.add_argument("image", type=Path, help="Input image path")
    parser.add_argument("--generator", required=True, help="Generator name")
    parser.add_argument(
        "--output",
        type=Path,
        help="Output path; omit to update the input image in place",
    )
    parser.add_argument("--font", help="Optional TrueType/OpenType font path")
    args = parser.parse_args()
    add_attribution(args.image, args.output or args.image, args.generator, args.font)


if __name__ == "__main__":
    main()
